# Generated by Django 4.2.1 on 2024-12-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('toyota', 'تويوتا'), ('nissan', 'نيسان'), ('honda', 'هوندا'), ('bmw', 'بي إم دبليو'), ('mercedes', 'مرسيدس'), ('audi', 'أودي'), ('chevrolet', 'شيفروليه'), ('hyundai', 'هيونداي'), ('kia', 'كيا'), ('ford', 'فورد'), ('volkswagen', 'فولكس واجن'), ('peugeot', 'بيجو'), ('renault', 'رينو'), ('mazda', 'مازدا'), ('suzuki', 'سوزوكي'), ('volvo', 'فولفو'), ('porsche', 'بورش'), ('land_rover', 'لاند روفر'), ('jaguar', 'جاجوار'), ('tesla', 'تسلا'), ('mitsubishi', 'ميتسوبيشي'), ('subaru', 'سوبارو'), ('gmc', 'جي إم سي'), ('cadillac', 'كاديلاك'), ('lincoln', 'لينكولن'), ('chrysler', 'كرايسلر'), ('dodge', 'دودج'), ('jeep', 'جيب'), ('fiat', 'فيات'), ('alfa_romeo', 'ألفا روميو'), ('ferrari', 'فيراري'), ('lamborghini', 'لامبورجيني'), ('aston_martin', 'أستون مارتن'), ('bentley', 'بنتلي'), ('rolls_royce', 'رولز رويس'), ('maserati', 'مازيراتي'), ('bugatti', 'بوجاتي'), ('infiniti', 'إنفينيتي'), ('lexus', 'لكزس'), ('acura', 'أكيورا'), ('saab', 'ساب'), ('skoda', 'سكودا'), ('seat', 'سيات'), ('opel', 'أوبل'), ('citroen', 'ستروين'), ('geely', 'جيلي'), ('mg', 'إم جي'), ('chery', 'شيري'), ('great_wall', 'جريت وول'), ('byd', 'بي واي دي'), ('jac', 'جاك'), ('haval', 'هافال'), ('baic', 'بايك'), ('zotye', 'زوتي'), ('ssangyong', 'سانغ يونغ')], max_length=20, verbose_name='الماركة')),
                ('model', models.CharField(max_length=50, verbose_name='الموديل')),
                ('type', models.CharField(max_length=50, verbose_name='النوع')),
                ('category', models.CharField(choices=[('E_HEV', 'E HEV'), ('XLE', 'XLE'), ('LE', 'LE'), ('SE', 'SE'), ('LIMITED', 'Limited'), ('SPORT', 'Sport'), ('HYBRID', 'Hybrid')], max_length=20, verbose_name='الفئة')),
                ('exterior_color', models.CharField(choices=[('white', 'أبيض'), ('black', 'أسود'), ('silver', 'فضي'), ('gray', 'رمادي'), ('blue', 'أزرق'), ('red', 'أحمر'), ('green', 'أخضر'), ('yellow', 'أصفر'), ('brown', 'بني'), ('beige', 'بيج'), ('orange', 'برتقالي'), ('gold', 'ذهبي'), ('purple', 'بنفسجي'), ('pink', 'وردي')], max_length=20, verbose_name='اللون الخارجي')),
                ('interior_color', models.CharField(choices=[('beige', 'بيج'), ('black', 'أسود'), ('gray', 'رمادي'), ('brown', 'بني'), ('white', 'أبيض'), ('red', 'أحمر'), ('blue', 'أزرق'), ('tan', 'لون الجلد الطبيعي'), ('ivory', 'عاجي'), ('chocolate', 'شوكولاتي'), ('dark_gray', 'رمادي غامق'), ('light_gray', 'رمادي فاتح'), ('cream', 'كريمي'), ('orange', 'برتقالي'), ('green', 'أخضر'), ('purple', 'بنفسجي'), ('custom', 'اخرى')], max_length=20, verbose_name='اللون الداخلي')),
                ('origin', models.CharField(max_length=50, verbose_name='الوارد')),
                ('fuel_type', models.CharField(choices=[('hybrid', 'هايبرد/هجين'), ('petrol', 'بنزين'), ('diesel', 'ديزل'), ('electric', 'كهرباء')], max_length=20, verbose_name='نوع الوقود')),
                ('transmission_type', models.CharField(choices=[('manual', 'يدوي'), ('automatic', 'أوتوماتيك'), ('cvt', 'CVT')], max_length=20, verbose_name='نوع القير')),
                ('cylinder_count', models.PositiveIntegerField(verbose_name='عدد السلندرات')),
                ('condition', models.CharField(choices=[('new', 'جديدة'), ('used', 'مستعملة')], max_length=10, verbose_name='الحالة')),
                ('engine_capacity', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='حجم المحرك')),
                ('drivetrain', models.CharField(choices=[('fwd', 'FWD دفع امامي'), ('rwd', 'RWD دفع خلفي'), ('awd', 'AWD دفع رباعي مستمر'), ('4wd', '4WD دفع رباعي قابل للتحكم')], max_length=20, verbose_name='نوع الدفع')),
                ('keys_count', models.PositiveIntegerField(verbose_name='عدد مفاتيح السيارة')),
                ('seat_count', models.PositiveIntegerField(verbose_name='عدد المقاعد')),
                ('engine_type', models.CharField(choices=[('natural', 'تنفس طبيعي'), ('turbo', 'تيربو'), ('supercharged', 'سوبر تشارج')], max_length=20, verbose_name='نوع المحرك')),
                ('fuel_tank_capacity', models.PositiveIntegerField(verbose_name='سعة خزان الوقود (لتر)')),
                ('horsepower', models.PositiveIntegerField(verbose_name='القدرة بالحصان')),
                ('door_count', models.PositiveIntegerField(verbose_name='عدد الابواب')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='car_icons/', verbose_name='الأيقونة')),
            ],
        ),
    ]
