# Generated by Django 4.2.1 on 2024-12-29 16:55

import customer.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='car_id',
            field=models.CharField(default=customer.models.RandomCarIDGen, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='price',
            field=models.DecimalField(decimal_places=3, help_text='سعر السيارة', max_digits=10, null=True, verbose_name='السعر'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='provider',
            field=models.ForeignKey(help_text='صاحب السيارة', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.CharField(choices=[('toyota', 'تويوتا'), ('nissan', 'نيسان'), ('honda', 'هوندا'), ('bmw', 'بي إم دبليو'), ('mercedes', 'مرسيدس'), ('audi', 'أودي'), ('chevrolet', 'شيفروليه'), ('hyundai', 'هيونداي'), ('kia', 'كيا'), ('ford', 'فورد'), ('volkswagen', 'فولكس واجن'), ('peugeot', 'بيجو'), ('renault', 'رينو'), ('mazda', 'مازدا'), ('suzuki', 'سوزوكي'), ('volvo', 'فولفو'), ('porsche', 'بورش'), ('land_rover', 'لاند روفر'), ('jaguar', 'جاجوار'), ('tesla', 'تسلا'), ('mitsubishi', 'ميتسوبيشي'), ('subaru', 'سوبارو'), ('gmc', 'جي إم سي'), ('cadillac', 'كاديلاك'), ('lincoln', 'لينكولن'), ('chrysler', 'كرايسلر'), ('dodge', 'دودج'), ('jeep', 'جيب'), ('fiat', 'فيات'), ('alfa_romeo', 'ألفا روميو'), ('ferrari', 'فيراري'), ('lamborghini', 'لامبورجيني'), ('aston_martin', 'أستون مارتن'), ('bentley', 'بنتلي'), ('rolls_royce', 'رولز رويس'), ('maserati', 'مازيراتي'), ('bugatti', 'بوجاتي'), ('infiniti', 'إنفينيتي'), ('lexus', 'لكزس'), ('acura', 'أكيورا'), ('saab', 'ساب'), ('skoda', 'سكودا'), ('seat', 'سيات'), ('opel', 'أوبل'), ('citroen', 'ستروين'), ('geely', 'جيلي'), ('mg', 'إم جي'), ('chery', 'شيري'), ('great_wall', 'جريت وول'), ('byd', 'بي واي دي'), ('jac', 'جاك'), ('haval', 'هافال'), ('baic', 'بايك'), ('zotye', 'زوتي'), ('ssangyong', 'سانغ يونغ')], help_text='اختر ماركة السيارة من الخيارات المتاحة.', max_length=20, verbose_name='الماركة'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='category',
            field=models.CharField(choices=[('E_HEV', 'E HEV'), ('XLE', 'XLE'), ('LE', 'LE'), ('SE', 'SE'), ('LIMITED', 'Limited'), ('SPORT', 'Sport'), ('HYBRID', 'Hybrid')], help_text='اختر الفئة التي تنتمي إليها السيارة (مثل: رياضية، عائلية، إلخ).', max_length=20, verbose_name='الفئة'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='condition',
            field=models.CharField(choices=[('new', 'جديدة'), ('used', 'مستعملة')], help_text='اختر حالة السيارة (جديدة، مستعملة، إلخ).', max_length=10, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='cylinder_count',
            field=models.PositiveIntegerField(help_text='أدخل عدد السلندرات في المحرك.', verbose_name='عدد السلندرات'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='door_count',
            field=models.PositiveIntegerField(help_text='أدخل عدد الأبواب في السيارة.', verbose_name='عدد الابواب'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='drivetrain',
            field=models.CharField(choices=[('fwd', 'FWD دفع امامي'), ('rwd', 'RWD دفع خلفي'), ('awd', 'AWD دفع رباعي مستمر'), ('4wd', '4WD دفع رباعي قابل للتحكم')], help_text='اختر نوع الدفع (دفع أمامي، دفع خلفي، دفع رباعي).', max_length=20, verbose_name='نوع الدفع'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='engine_capacity',
            field=models.DecimalField(decimal_places=1, help_text='أدخل حجم المحرك باللتر (مثال: 2.0).', max_digits=4, verbose_name='حجم المحرك'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='engine_type',
            field=models.CharField(choices=[('natural', 'تنفس طبيعي'), ('turbo', 'تيربو'), ('supercharged', 'سوبر تشارج')], help_text='اختر نوع المحرك (بنزين، كهربائي، هجين).', max_length=20, verbose_name='نوع المحرك'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='exterior_color',
            field=models.CharField(choices=[('white', 'أبيض'), ('black', 'أسود'), ('silver', 'فضي'), ('gray', 'رمادي'), ('blue', 'أزرق'), ('red', 'أحمر'), ('green', 'أخضر'), ('yellow', 'أصفر'), ('brown', 'بني'), ('beige', 'بيج'), ('orange', 'برتقالي'), ('gold', 'ذهبي'), ('purple', 'بنفسجي'), ('pink', 'وردي')], help_text='اختر اللون الخارجي للسيارة.', max_length=20, verbose_name='اللون الخارجي'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='fuel_tank_capacity',
            field=models.PositiveIntegerField(help_text='أدخل سعة خزان الوقود باللتر.', verbose_name='سعة خزان الوقود (لتر)'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='fuel_type',
            field=models.CharField(choices=[('hybrid', 'هايبرد/هجين'), ('petrol', 'بنزين'), ('diesel', 'ديزل'), ('electric', 'كهرباء')], help_text='اختر نوع الوقود المستخدم في السيارة (بنزين، ديزل، إلخ).', max_length=20, verbose_name='نوع الوقود'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='horsepower',
            field=models.PositiveIntegerField(help_text='أدخل قدرة المحرك بالحصان.', verbose_name='القدرة بالحصان'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='icon',
            field=models.ImageField(blank=True, help_text='اختر صورة الرئيسية التي ستظهر للسيارة (اختياري).', null=True, upload_to='car_icons/', verbose_name='الصورة الرئيسية'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='interior_color',
            field=models.CharField(choices=[('beige', 'بيج'), ('black', 'أسود'), ('gray', 'رمادي'), ('brown', 'بني'), ('white', 'أبيض'), ('red', 'أحمر'), ('blue', 'أزرق'), ('tan', 'لون الجلد الطبيعي'), ('ivory', 'عاجي'), ('chocolate', 'شوكولاتي'), ('dark_gray', 'رمادي غامق'), ('light_gray', 'رمادي فاتح'), ('cream', 'كريمي'), ('orange', 'برتقالي'), ('green', 'أخضر'), ('purple', 'بنفسجي'), ('custom', 'اخرى')], help_text='اختر اللون الداخلي للسيارة.', max_length=20, verbose_name='اللون الداخلي'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='keys_count',
            field=models.PositiveIntegerField(help_text='أدخل عدد المفاتيح المتاحة للسيارة.', verbose_name='عدد مفاتيح السيارة'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='model',
            field=models.CharField(help_text='أدخل موديل السيارة بشكل دقيق.', max_length=50, verbose_name='الموديل'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='origin',
            field=models.CharField(help_text='أدخل البلد الذي وردت منه السيارة.', max_length=50, verbose_name='الوارد'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='seat_count',
            field=models.PositiveIntegerField(help_text='أدخل عدد المقاعد في السيارة.', verbose_name='عدد المقاعد'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='transmission_type',
            field=models.CharField(choices=[('manual', 'يدوي'), ('automatic', 'أوتوماتيك'), ('cvt', 'CVT')], help_text='اختر نوع القير (يدوي، أوتوماتيك، إلخ).', max_length=20, verbose_name='نوع القير'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='type',
            field=models.CharField(help_text='أدخل نوع السيارة (مثل: سيدان، هاتشباك، إلخ).', max_length=50, verbose_name='النوع'),
        ),
    ]
