# Generated by Django 4.2.1 on 2024-12-29 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_carmodel_car_id_carmodel_price_carmodel_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='cars/images/%Y/%m/%d/')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.carmodel')),
            ],
        ),
    ]
