# Generated by Django 4.2.1 on 2024-12-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_carimagesmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carimagesmodel',
            name='car',
        ),
        migrations.AddField(
            model_name='carimagesmodel',
            name='car_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
