# Generated by Django 4.2.1 on 2024-12-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_carimagesmodel_car_carimagesmodel_car_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='title',
            field=models.CharField(help_text='عنوان قصير للسيارة', max_length=80, null=True, verbose_name='العنوان'),
        ),
    ]
