# Generated by Django 4.2.1 on 2025-01-04 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0006_buycarordermodel_ordermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_orders', to=settings.AUTH_USER_MODEL, verbose_name='العميل'),
        ),
    ]
