# Generated by Django 4.2.1 on 2025-01-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_ordermodel_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buycarordermodel',
            name='car_year',
        ),
        migrations.AlterField(
            model_name='buycarordermodel',
            name='car_model',
            field=models.CharField(max_length=50, verbose_name='سنة الصنع'),
        ),
        migrations.AlterField(
            model_name='buycarordermodel',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'قيد التنفيذ'), ('shipped', 'يتم الشحن'), ('delivered', 'تم التسليم'), ('canceled', 'ملغى')], default='pending', max_length=20, verbose_name='حالة الطلب'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='model',
            field=models.CharField(help_text='أدخل سنة الصنع السيارة بشكل دقيق.', max_length=50, verbose_name='سنة الصنع'),
        ),
    ]
