# Generated by Django 4.2.1 on 2025-01-04 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_remove_buycarordermodel_car_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buycarordermodel',
            old_name='customer',
            new_name='car',
        ),
    ]
