# Generated by Django 4.2.1 on 2025-01-04 16:18

import customer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_rename_customer_buycarordermodel_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='car_id',
            field=models.CharField(default=customer.models.RandomOrderIDGen, max_length=50, null=True),
        ),
    ]
