# Generated by Django 4.2.1 on 2025-01-06 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_rename_car_id_ordermodel_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='ماركة السيارة')),
                ('model', models.CharField(max_length=50, verbose_name='موديل السيارة')),
                ('year', models.PositiveIntegerField(verbose_name='سنة الصنع')),
                ('condition', models.CharField(choices=[('new', 'جديدة'), ('used', 'مستعملة')], max_length=20, verbose_name='الحالة')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر السيارة')),
                ('country_of_origin', models.CharField(max_length=50, verbose_name='بلد المنشأ')),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='تكلفة الشحن')),
            ],
            options={
                'verbose_name': 'سيارة للاستيراد',
                'verbose_name_plural': 'سيارات للاستيراد',
            },
        ),
        migrations.CreateModel(
            name='ShippingCompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم شركة الشحن')),
                ('contact_info', models.TextField(verbose_name='معلومات الاتصال')),
                ('tracking_url', models.URLField(verbose_name='رابط التتبع')),
            ],
            options={
                'verbose_name': 'شركة شحن',
                'verbose_name_plural': 'شركات الشحن',
            },
        ),
        migrations.RemoveField(
            model_name='buycarordermodel',
            name='car_brand',
        ),
        migrations.RemoveField(
            model_name='buycarordermodel',
            name='car_model',
        ),
        migrations.RemoveField(
            model_name='buycarordermodel',
            name='color',
        ),
        migrations.RemoveField(
            model_name='buycarordermodel',
            name='price',
        ),
        migrations.AlterField(
            model_name='buycarordermodel',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_model', to='customer.carmodel', verbose_name='السيارة'),
        ),
        migrations.AddField(
            model_name='buycarordermodel',
            name='car_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_import_model', to='customer.carimportmodel', verbose_name='السيارة'),
        ),
        migrations.AlterField(
            model_name='buycarordermodel',
            name='shipping_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.shippingcompanymodel', verbose_name='شركة الشحن'),
        ),
    ]
