# Generated by Django 4.2.1 on 2025-01-08 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_remove_carimportmodel_shipping_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRentalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الإيجار اليومي')),
                ('weekly_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الإيجار الأسبوعي')),
                ('monthly_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الإيجار الشهري')),
                ('availability', models.BooleanField(default=True, verbose_name='متاحة للتأجير')),
            ],
        ),
        migrations.AddField(
            model_name='carmodel',
            name='offered',
            field=models.CharField(choices=[('1', 'للبيع'), ('2', 'للايجار')], default='1', help_text='اختر نوع عرض السيارة من الخيارات المتاحة.', max_length=20, verbose_name='معروض'),
        ),
        migrations.AlterField(
            model_name='buycarordermodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم الكامل'),
        ),
        migrations.CreateModel(
            name='RentalOrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='اسم العميل')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('customer_phone', models.CharField(max_length=15, verbose_name='رقم الهاتف')),
                ('start_date', models.DateField(verbose_name='تاريخ بدء الإيجار')),
                ('end_date', models.DateField(verbose_name='تاريخ انتهاء الإيجار')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'مؤكد'), ('completed', 'مكتمل'), ('canceled', 'ملغى')], default='pending', max_length=20, verbose_name='حالة الحجز')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='التكلفة الإجمالية')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية')),
                ('car_rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.carrentalmodel', verbose_name='السيارة المحجوزة')),
            ],
            options={
                'verbose_name': 'حجز',
                'verbose_name_plural': 'حجوزات',
            },
        ),
        migrations.AddField(
            model_name='carrentalmodel',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.carmodel', verbose_name='السيارة'),
        ),
    ]
