# Generated by Django 4.2.1 on 2025-01-08 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_carrentalmodel_carmodel_offered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalordermodel',
            name='rental_days',
            field=models.CharField(choices=[('1', 'يومي'), ('7', 'أسبوعي'), ('30', 'شهري')], max_length=20, null=True, verbose_name='عدد أيام الإيجار'),
        ),
        migrations.AlterField(
            model_name='carrentalmodel',
            name='availability',
            field=models.BooleanField(default=True, help_text='عرض السيارة ضمن قائمة السيارات الأيجار', verbose_name='متاحة للتأجير'),
        ),
    ]
