# Generated by Django 4.2.1 on 2025-01-08 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_rentalordermodel_rental_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='car_rental_order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.rentalordermodel', verbose_name='مودل طلب شراء السيارة'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='order_type',
            field=models.CharField(choices=[('buy_car', 'شراء سيارة'), ('car_import', 'استراد السيارة'), ('car_rental', 'ايجار السيارة')], max_length=20, verbose_name='نوع الطلب'),
        ),
    ]
