# Generated by Django 4.2.1 on 2025-01-09 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_alter_ordermodel_buy_car_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalordermodel',
            name='address',
            field=models.TextField(null=True, verbose_name='عنوان التسليم'),
        ),
        migrations.AlterField(
            model_name='rentalordermodel',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'جاري التدقيق'), ('confirmed', 'مؤكد'), ('completed', 'مكتمل'), ('canceled', 'ملغى')], default='pending', max_length=20, verbose_name='حالة الحجز'),
        ),
    ]
