# Generated by Django 4.2.1 on 2025-01-12 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_financingplanmodel_installmentpayment_latepayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='car_installment_order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.installmentrequestmodel', verbose_name='مودل طلب تقسيط السيارة'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='offered',
            field=models.CharField(choices=[('1', 'للبيع'), ('2', 'للايجار'), ('3', 'للتقسيط')], default='1', help_text='اختر نوع عرض السيارة من الخيارات المتاحة.', max_length=20, verbose_name='معروض'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='car_rental_order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.rentalordermodel', verbose_name='مودل طلب ايجار السيارة'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='order_type',
            field=models.CharField(choices=[('buy_car', 'شراء سيارة'), ('car_import', 'استراد السيارة'), ('car_rental', 'ايجار السيارة'), ('car_installment', 'تقسيط السيارة')], max_length=20, verbose_name='نوع الطلب'),
        ),
    ]
