# Generated by Django 4.2.1 on 2025-01-12 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_ordermodel_car_installment_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installmentrequestmodel',
            name='customer',
        ),
        migrations.AddField(
            model_name='installmentrequestmodel',
            name='customer_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='installmentrequestmodel',
            name='customer_name',
            field=models.CharField(max_length=100, null=True, verbose_name='اسم العميل'),
        ),
        migrations.AddField(
            model_name='installmentrequestmodel',
            name='customer_phone',
            field=models.CharField(max_length=15, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AddField(
            model_name='installmentrequestmodel',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية'),
        ),
    ]
