# Generated by Django 4.2.1 on 2025-01-17 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0022_remove_installmentrequestmodel_duration_months_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentpayment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='installmentpayment',
            name='status',
            field=models.CharField(choices=[('paid', 'مدفوع'), ('pending', 'قيد انتظار الطلب'), ('late', 'متأخر')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='installmentrequestmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='اسم العميل')),
                ('amount', models.DecimalField(decimal_places=3, help_text='مبلغ المدفوع', max_digits=10, null=True, verbose_name='المبلغ')),
                ('action_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='العميل')),
            ],
        ),
    ]
