# Generated by Django 4.2.1 on 2025-01-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_alter_installmentpayment_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistorymodel',
            name='order_type',
            field=models.CharField(choices=[('1', 'دفع'), ('2', 'شحن')], max_length=20, null=True, verbose_name='نوع الطلب'),
        ),
    ]
