# Generated by Django 4.2.1 on 2025-01-19 00:54

import customer.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0024_paymenthistorymodel_order_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_type', models.CharField(choices=[('individual', 'فرد'), ('company', 'شركة')], max_length=20, verbose_name='نوع المزود')),
                ('name', models.CharField(max_length=255, verbose_name='نوع المركبة')),
                ('capacity', models.CharField(max_length=100, verbose_name='الحمولة (طن)')),
                ('model', models.CharField(max_length=50, verbose_name='موديل المركبة')),
                ('year', models.PositiveIntegerField(verbose_name='سنة الصنع')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('license_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الرخصة')),
                ('license_plate', models.CharField(max_length=20, verbose_name='رقم اللوحة')),
                ('car_id', models.CharField(default=customer.models.RandomVehicleIDGen, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, help_text='اختر صورة الرئيسية التي ستظهر للسيارة (اختياري).', null=True, upload_to='vehicles/', verbose_name='الصورة الرئيسية')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المالك')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الخدمة')),
                ('category', models.CharField(choices=[('heavy_transport', 'نقل معدات ثقيلة'), ('cargo_transport', 'نقل بضائع'), ('furniture_transport', 'نقل أثاث'), ('refrigerated_transport', 'نقل مبرد'), ('raw_material_transport', 'نقل مواد أولية'), ('water_transport', 'نقل مياه'), ('waste_transport', 'نقل صرف صحي'), ('container_transport', 'نقل حاويات')], max_length=50, verbose_name='فئة الخدمة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الخدمة')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الأساسي')),
            ],
        ),
        migrations.AlterModelOptions(
            name='paymenthistorymodel',
            options={'ordering': ['-id']},
        ),
        migrations.CreateModel(
            name='VehicleRentalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=255, verbose_name='نقطة البداية')),
                ('end_location', models.CharField(max_length=255, verbose_name='نقطة الوصول')),
                ('date', models.DateField(verbose_name='تاريخ الخدمة')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='وقت الخدمة')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='التكلفة الإجمالية')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'تم التأكيد'), ('completed', 'مكتمل')], default='pending', max_length=20, verbose_name='حالة الطلب')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.vehicleservice', verbose_name='الخدمة المطلوبة')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.vehiclemodel', verbose_name='المركبة')),
            ],
        ),
    ]
