# Generated by Django 4.2.1 on 2025-01-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0025_vehiclemodel_vehicleservice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=50, null=True)),
                ('img', models.FileField(upload_to='vehicle/images/%Y/%m/%d/')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
