# Generated by Django 4.2.1 on 2025-01-19 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0026_vehicleimagesmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclemodel',
            old_name='car_id',
            new_name='vehicle_id',
        ),
    ]
