# Generated by Django 4.2.1 on 2025-01-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0027_rename_car_id_vehiclemodel_vehicle_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemodel',
            name='brand',
            field=models.CharField(help_text='ادخل ماركة المركبة.', max_length=20, null=True, verbose_name='الماركة'),
        ),
    ]
