# Generated by Django 4.2.1 on 2025-01-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0028_vehiclemodel_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemodel',
            name='origin',
            field=models.CharField(help_text='أدخل البلد الذي يوجد فيه المركبة.', max_length=50, null=True, verbose_name='الوارد'),
        ),
    ]
