# Generated by Django 4.2.1 on 2025-01-19 21:05

import customer.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0029_vehiclemodel_origin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiclemodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'مركبة', 'verbose_name_plural': 'المركبات'},
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='loading_cost',
            field=models.DecimalField(decimal_places=2, default=20, help_text='رسوم التحميل الإضافية.', max_digits=10, verbose_name='رسوم التحميل'),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='price_per_km',
            field=models.DecimalField(decimal_places=2, default=5, help_text='سعر النقل لكل كيلومتر.', max_digits=10, verbose_name='سعر الكيلومتر'),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='unloading_cost',
            field=models.DecimalField(decimal_places=2, default=20, help_text='رسوم التفريغ الإضافية.', max_digits=10, verbose_name='رسوم التفريغ'),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاريخ التعديل'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='capacity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(100)], verbose_name='الحمولة (طن)'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='image',
            field=models.ImageField(blank=True, help_text='اختر صورة السيارة بأبعاد لا تزيد عن 1024x1024 بكسل.', null=True, upload_to='vehicles/', verbose_name='الصورة الرئيسية'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='license_plate',
            field=models.CharField(max_length=20, unique=True, verbose_name='رقم اللوحة'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='vehicle_id',
            field=models.CharField(default=customer.models.RandomVehicleIDGen, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='سنة الصنع'),
        ),
    ]
