# Generated by Django 4.2.1 on 2025-01-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0030_alter_vehiclemodel_options_vehiclemodel_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclerentalorder',
            name='km_count',
            field=models.PositiveIntegerField(help_text='المسافة التي سوف يقطعها الحاملة', null=True, verbose_name='المسافة بالكيلومتر'),
        ),
    ]
