# Generated by Django 4.2.1 on 2025-01-19 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0032_ordermodel_vehicle_rental_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclerentalorder',
            name='customer_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='vehiclerentalorder',
            name='customer_name',
            field=models.CharField(max_length=100, null=True, verbose_name='اسم العميل'),
        ),
        migrations.AddField(
            model_name='vehiclerentalorder',
            name='customer_phone',
            field=models.CharField(max_length=15, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AddField(
            model_name='vehiclerentalorder',
            name='end_address',
            field=models.TextField(null=True, verbose_name='عنوان التفريغ'),
        ),
        migrations.AddField(
            model_name='vehiclerentalorder',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية'),
        ),
        migrations.AddField(
            model_name='vehiclerentalorder',
            name='start_address',
            field=models.TextField(null=True, verbose_name='عنوان التحميل'),
        ),
        migrations.AlterField(
            model_name='vehiclerentalorder',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'تم التأكيد'), ('completed', 'مكتمل'), ('canceled', 'ملغى')], default='pending', max_length=20, verbose_name='حالة الطلب'),
        ),
    ]
