# Generated by Django 4.2.1 on 2025-01-19 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0033_vehiclerentalorder_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclerentalorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AddField(
            model_name='vehiclerentalorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاريخ التعديل'),
        ),
    ]
