# Generated by Django 4.2.1 on 2025-01-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0034_vehiclerentalorder_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='model',
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='dimensions',
            field=models.CharField(help_text='أدخل أبعاد المركبة (الطول × العرض × الارتفاع).', max_length=100, null=True, verbose_name='الحجم (مم)'),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='empty_weight',
            field=models.PositiveIntegerField(help_text='أدخل الوزن الفارغ للشاحنة بالكيلوجرام.', null=True, verbose_name='وزن الشاحنة فارغة (كجم)'),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='energy_type',
            field=models.CharField(choices=[('hybrid', 'هايبرد/هجين'), ('petrol', 'بنزين'), ('diesel', 'ديزل'), ('electric', 'كهرباء'), ('other', 'أخرى')], help_text='اختر نوع الطاقة المستخدمة.', max_length=20, null=True, verbose_name='نوع الطاقة'),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='max_power',
            field=models.DecimalField(decimal_places=2, help_text='ادخل أقصى قوة للمركبة بالكيلوواط.', max_digits=10, null=True, verbose_name='أقصى قوة (kw)'),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='model_number',
            field=models.CharField(help_text='ادخل رقم الموديل للمركبة.', max_length=50, null=True, verbose_name='رقم الموديل'),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='truck_category',
            field=models.CharField(choices=[('small', 'شاحنة صغيرة'), ('medium', 'شاحنة متوسطة'), ('large', 'شاحنة كبيرة'), ('special', 'شاحنة خاصة')], help_text='اختر فئة الشاحنة.', max_length=20, null=True, verbose_name='فئة الشاحنات'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='fuel_type',
            field=models.CharField(choices=[('hybrid', 'هايبرد/هجين'), ('petrol', 'بنزين'), ('diesel', 'ديزل'), ('electric', 'كهرباء'), ('other', 'أخرى')], help_text='اختر نوع الوقود المستخدم في السيارة (بنزين، ديزل، إلخ).', max_length=20, verbose_name='نوع الوقود'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='brand',
            field=models.CharField(help_text='ادخل اسم العلامة التجارية للمركبة.', max_length=20, null=True, verbose_name='اسم العلامة التجارية'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='origin',
            field=models.CharField(help_text='أدخل البلد الذي تم تصنيع المركبة فيه.', max_length=50, null=True, verbose_name='مكان المنشأ'),
        ),
    ]
