# Generated by Django 4.2.1 on 2025-01-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0035_remove_vehiclemodel_model_vehiclemodel_dimensions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5, help_text='سعر المركبة.', max_digits=10, verbose_name='السعر'),
        ),
    ]
