# Generated by Django 4.2.1 on 2025-01-21 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0036_vehiclemodel_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyVehicleOrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الكامل')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=15, verbose_name='رقم الهاتف')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التسليم المتوقع')),
                ('address', models.TextField(verbose_name='عنوان التسليم')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'قيد التنفيذ'), ('shipped', 'يتم الشحن'), ('delivered', 'تم التسليم'), ('canceled', 'ملغى')], default='pending', max_length=20, verbose_name='حالة الطلب')),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم التتبع')),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='تكلفة الشحن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('shipping_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.shippingcompanymodel', verbose_name='شركة الشحن')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_model', to='customer.vehiclemodel', verbose_name='السيارة')),
            ],
            options={
                'verbose_name': 'طلب سيارة',
                'verbose_name_plural': 'طلبات السيارات',
                'ordering': ['-order_date'],
            },
        ),
    ]
