# Generated by Django 4.2.1 on 2025-01-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='balance',
            field=models.DecimalField(decimal_places=3, default=0, help_text='رصيدك الحالي', max_digits=10, verbose_name='الرصيد'),
        ),
    ]
