# Generated by Django 4.2.1 on 2025-01-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_dealerprofile_img_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerprofile',
            name='city',
            field=models.CharField(max_length=100, null=True, verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الموقع الجغرافي'),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ساعات العمل'),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ التسجيل'),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='الموقع الإلكتروني'),
        ),
    ]
