from django.urls import path
from . import views

urlpatterns = [
    path('Home', views.Home, name='CustomerHome'),
    path('buy_cars', views.buy_cars, name='buy_cars'),
    path('for_sell_vehicles', views.for_sell_vehicles, name='for_sell_vehicles'),
    path('your_for_sell_vehicles', views.your_for_sell_vehicles, name='your_for_sell_vehicles'),
    path('view_for_sell_vehicle/<int:id>', views.view_for_sell_vehicle, name='view_for_sell_vehicle'),
    path('add_for_sell_vehicle', views.add_for_sell_vehicle, name='add_for_sell_vehicle'),
    path('edit_for_sell_vehicle/<int:vehicle_id>', views.edit_for_sell_vehicle, name='edit_for_sell_vehicle'),
    path('rental_vehicles', views.rental_vehicles, name='rental_vehicles'),
    path('your_rental_vehicles', views.your_rental_vehicles, name='your_rental_vehicles'),
    path('add_your_rental_vehicle', views.add_your_rental_vehicle, name='add_your_rental_vehicle'),
    path('view_rental_vehicle/<int:id>', views.view_rental_vehicle, name='view_rental_vehicle'),
    path('edit_rental_vehicle/<int:vehicle_id>', views.edit_rental_vehicle, name='edit_rental_vehicle'),
    path('installment_cars', views.installment_cars, name='installment_cars'),
    path('rental_cars', views.rental_cars, name='rental_cars'),
    path('order_buy_car/<int:id>', views.order_buy_car, name='order_buy_car'),
    path('order_buy_vehicle/<int:id>', views.order_buy_vehicle, name='order_buy_vehicle'),
    path('order_car_rental/<int:id>', views.order_car_rental, name='order_car_rental'),
    path('order_car_installment/<int:id>', views.order_car_installment, name='order_car_installment'),
    path('order_vehicle_rental/<int:vehicle_id>', views.order_vehicle_rental, name='order_vehicle_rental'),
    path('order_car_import/', views.order_car_import, name='order_car_import'),
    path('view_buy_car_order/<int:order_id>', views.view_buy_car_order, name='view_buy_car_order'),
    path('view_buy_vehicle_order/<int:order_id>', views.view_buy_vehicle_order, name='view_buy_vehicle_order'),
    path('view_vehicle_rental_order/<int:order_id>', views.view_vehicle_rental_order, name='view_vehicle_rental_order'),
    path('view_rental_car_order/<int:order_id>', views.view_rental_car_order, name='view_rental_car_order'),
    path('view_installment_car_order/<int:order_id>', views.view_installment_car_order, name='view_installment_car_order'),
    path('view_car/<int:id>', views.view_car, name='view_car'),
    path('installment_view_car/<int:id>', views.installment_view_car, name='installment_view_car'),
    path('view_rental_car/<int:id>', views.view_rental_car, name='view_rental_car'),
    path('edit_car/<int:car_id>', views.edit_car, name='edit_car'),
    path('add_car_for_sell/', views.add_car_for_sell, name='add_car_for_sell'),
    path('add_car_for_rental/', views.add_car_for_rental, name='add_car_for_rental'),
    path('your_cars/', views.your_cars, name='your_cars'),
    path('your_rental_cars/', views.your_rental_cars, name='your_rental_cars'),
    path('your_orders/', views.your_orders, name='your_orders'),
    path('UploadCarImage/<str:car_id>', views.UploadCarImage, name='UploadCarImage'),
    path('UploadVehicleImage/<str:vehicle_id>', views.UploadVehicleImage, name='UploadVehicleImage'),
    path('GetVehicleRentalPrice/<str:vehicle_id>', views.GetVehicleRentalPrice, name='GetVehicleRentalPrice'),
    path('delete_car_img/', views.delete_car_img, name='delete_car_img'),

]
